📋 Script initialized successfully.
  [SubmittedPet] : (Table)
    [PetData] : (Table)
      [HatchedFrom] : Paradise Egg
      [LevelProgress] : 0
      [Name] : Geo
      [Level] : 110
      [BaseWeight] : 5.550825977532712
      [Boosts] : (Table)
      [Hunger] : 17940.756945750756
      [MutationType] : P
    [UUID] : {187f11e7-1563-4a6b-9446-67502976840f}
    [PetType] : Mimic Octopus
  [PetReady] : false
  [TimeLeft] : 0
  [IsRunning] : false
  
  
  